# Generated by Django 2.2.6 on 2019-12-21 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='entry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
