# Generated by Django 2.2.6 on 2020-07-19 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20200719_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='created_on',
        ),
    ]
