# Generated by Django 2.2.6 on 2019-11-11 18:13

import animals.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('breedingcows', '0005_auto_20191111_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flock_number', models.IntegerField(blank=True, default=0, null=True)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('entry_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('leaving_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_date', models.DateTimeField(blank=True, null=True)),
                ('weight', models.DecimalField(decimal_places=15, max_digits=30)),
                ('reproductive_status', models.IntegerField(choices=[('Positivo', 'POSITIVO'), ('Negativo', 'NEGATIVO')], default=animals.models.ReproductiveStatus('Positivo'))),
                ('animal_type', models.IntegerField(choices=[('Vaca', 'VACA'), ('Vaquillona', 'VAQUILLONA'), ('Toro', 'TORO'), ('Ternero', 'TERNERO')], default=animals.models.AnimalType('Ternero'))),
                ('breeding_cows', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='breedingcows.BreedingCows')),
            ],
        ),
        migrations.CreateModel(
            name='AnimalDisease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_date', models.DateTimeField(blank=True, null=True)),
                ('diagnosis', models.IntegerField(blank=True, choices=[('Quiste', 'QUISTE'), ('Atrofia', 'ATROFIA'), ('Falta de Desarrollo', 'DESARROLLO')], null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.Animals')),
            ],
        ),
    ]
