# Generated by Django 2.2.6 on 2020-02-22 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0001_initial'),
        ('animals', '0002_auto_20191111_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='flock_number',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='animals',
            name='weight',
            field=models.DecimalField(decimal_places=15, default='', max_digits=30),
        ),
        migrations.CreateModel(
            name='AnimalDiet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_date', models.DateTimeField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.Animals')),
                ('diet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diets.Diet')),
            ],
        ),
    ]
