# Generated by Django 2.2.6 on 2020-03-03 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_auto_20200222_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='animals',
            name='sexual_maturity',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
