# Generated by Django 2.2.6 on 2020-03-05 01:52

import animals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_animals_sexual_maturity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animaldisease',
            name='diagnosis_date',
        ),
        migrations.AlterField(
            model_name='animals',
            name='reproductive_status',
            field=models.CharField(choices=[('Vaca', 'VACA'), ('Vaquillona', 'VAQUILLONA'), ('Toro', 'TORO'), ('Ternero', 'TERNERO')], default=animals.models.AnimalType('Ternero'), max_length=100),
        ),
    ]
