# Generated by Django 2.2.6 on 2020-04-29 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_auto_20200304_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='animals',
            name='body_development',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
