# Generated by Django 2.2.6 on 2020-05-03 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reproduction', '0003_auto_20200503_1808'),
        ('animals', '0006_animals_body_development'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalRepoduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_date', models.DateTimeField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.Animals')),
                ('reproduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reproduction.Reproduction')),
            ],
        ),
    ]
