# Generated by Django 2.2.6 on 2020-05-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0007_animalrepoduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalrepoduction',
            name='finished_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
