# Generated by Django 2.2.6 on 2020-05-03 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breedingcows', '0009_breedingcows_contact'),
        ('animals', '0008_animalrepoduction_finished_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalrepoduction',
            name='breeding_cow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='breedingcows.BreedingCows'),
        ),
    ]
