# Generated by Django 2.2.6 on 2020-05-12 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0009_animalrepoduction_breeding_cow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animals',
            name='reproductive_status',
        ),
    ]
