# Generated by Django 2.2.6 on 2020-05-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0010_remove_animals_reproductive_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='animals',
            name='acquisition',
            field=models.CharField(choices=[('Inseminacio Artificial a tiempo fijo', 'INSEMINACION'), ('Monta natural', 'NATURAL'), ('Compra', 'COMPRA')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='animals',
            name='parents',
            field=models.ManyToManyField(default='', related_name='_animals_parents_+', to='animals.Animals'),
        ),
    ]
