# Generated by Django 2.2.6 on 2020-05-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0011_auto_20200514_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animals',
            name='parents',
        ),
        migrations.AddField(
            model_name='animals',
            name='brood',
            field=models.ManyToManyField(blank=True, null=True, related_name='_animals_brood_+', to='animals.Animals'),
        ),
        migrations.AlterField(
            model_name='animals',
            name='acquisition',
            field=models.CharField(choices=[('Monta natural', 'NATURAL'), ('Compra', 'COMPRA'), ('Inseminacio Artificial a tiempo fijo', 'INSEMINACION')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='animals',
            name='flock_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
