# Generated by Django 2.2.6 on 2020-05-25 19:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0013_auto_20200524_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animaldiet',
            name='diagnosis_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animalrepoduction',
            name='finished_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animalrepoduction',
            name='started_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animals',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animals',
            name='entry_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='animals',
            name='leaving_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animals',
            name='rejection_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
