# Generated by Django 2.2.6 on 2020-05-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0014_auto_20200525_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='entry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
