# Generated by Django 2.2.6 on 2020-05-26 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0016_animalsanitary'),
    ]

    operations = [
        migrations.AddField(
            model_name='animals',
            name='disease',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animals',
            name='disease_description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
