# Generated by Django 3.1.4 on 2021-01-25 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0018_auto_20200916_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='brood',
            field=models.ManyToManyField(related_name='children', to='animals.Animals'),
        ),
    ]
