# Generated by Django 2.2.6 on 2020-05-25 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sanitarybook.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sanitary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('antiparasitic', models.DecimalField(decimal_places=2, default='', max_digits=5)),
                ('copper', models.DecimalField(decimal_places=2, default='', max_digits=5)),
                ('clostridiosis', models.DecimalField(decimal_places=2, default='', max_digits=5)),
                ('description', models.CharField(default='', max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('animal_type', models.CharField(choices=[('Vaca', 'VACA'), ('Vaquillona', 'VAQUILLONA'), ('Toro', 'TORO'), ('Ternero', 'TERNERO')], default=sanitarybook.models.AnimalType('Ternero'), max_length=100)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
