# Generated by Django 2.2.6 on 2020-05-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanitarybook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanitary',
            name='antiparasitic',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
