# Generated by Django 3.1.4 on 2021-01-25 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanitarybook', '0002_auto_20200525_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanitary',
            name='antiparasitic',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sanitary',
            name='clostridiosis',
            field=models.DecimalField(blank=True, decimal_places=2, default='', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='sanitary',
            name='copper',
            field=models.DecimalField(blank=True, decimal_places=2, default='', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='sanitary',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
