# Generated by Django 2.2.6 on 2020-05-03 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reproduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reproduction_type', models.CharField(choices=[('Inseminacion Artificial', 'INSEMINACION'), ('Natural', 'NATURAL')], default='', max_length=100)),
                ('preparation_created_date', models.DateTimeField(blank=True, null=True)),
                ('execution_date', models.DateTimeField(blank=True, null=True)),
                ('revision_date', models.DateTimeField(blank=True, null=True)),
                ('success', models.BooleanField(blank=True, null=True)),
                ('separation', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
