# Generated by Django 2.2.6 on 2020-05-03 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reproduction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reproduction',
            name='give_birth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
