# Generated by Django 2.2.6 on 2020-05-03 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reproduction', '0002_reproduction_give_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reproduction',
            old_name='preparation_created_date',
            new_name='preparation_date',
        ),
    ]
