# Generated by Django 2.2.6 on 2020-05-05 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reproduction', '0004_auto_20200505_2005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reproduction',
            old_name='success',
            new_name='success_revision',
        ),
    ]
