# Generated by Django 2.2.6 on 2020-05-30 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reproduction', '0005_auto_20200505_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reproduction',
            name='execution_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reproduction',
            name='give_birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reproduction',
            name='preparation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reproduction',
            name='revision_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reproduction',
            name='separation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
