# Generated by Django 2.2.6 on 2020-05-31 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reproduction', '0006_auto_20200530_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='reproduction',
            name='has_prostaglandin_vaccine',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reproduction',
            name='has_vaginal_device',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
