# Generated by Django 2.2.6 on 2020-06-07 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reproduction', '0007_auto_20200531_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='reproduction',
            name='potential_give_birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
