# Generated by Django 2.2.6 on 2020-07-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reproduction', '0008_reproduction_potential_give_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reproduction',
            name='next_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
