# Generated by Django 2.2.6 on 2020-10-12 00:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reproduction', '0012_auto_20201011_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reproduction',
            name='preparation_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 10, 11, 21, 56, 8, 679508), null=True),
        ),
    ]
