# Generated by Django 3.1.4 on 2021-01-25 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reproduction', '0013_auto_20201011_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reproduction',
            name='preparation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
