# Generated by Django 2.2.6 on 2019-11-11 20:11

import animals.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('breedingcows', '0006_auto_20191111_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=200)),
                ('animal_type', models.CharField(choices=[('Vaca', 'VACA'), ('Vaquillona', 'VAQUILLONA'), ('Toro', 'TORO'), ('Ternero', 'TERNERO')], default=animals.models.AnimalType('Ternero'), max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realization_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_date', models.DateTimeField(blank=True, null=True)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='action.ActionDefinition')),
                ('breeding_cows', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='breedingcows.BreedingCows')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
