# Generated by Django 2.2.6 on 2020-03-03 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0003_auto_20191111_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actiondetail',
            name='reproductive_status',
        ),
    ]
