# Generated by Django 2.2.6 on 2019-11-03 01:06

import breedingcows.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('breedingcows', '0002_breedingcows_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breedingcows',
            name='status',
            field=models.IntegerField(choices=[('Activo', 'ACTIVO'), ('Eliminado', 'ELIMINADO'), ('Suspendido', 'SUSPENDIDIO')], default=breedingcows.models.StatusType('Activo')),
        ),
        migrations.CreateModel(
            name='WorkPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(blank=True, null=True)),
                ('leaving_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('a', 'Activo'), ('e', 'Eliminado')], default='a', help_text='Estado del Rodeo de Cría', max_length=1)),
                ('breeding_cows', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breedingcows.BreedingCows')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
