# Generated by Django 2.2.6 on 2019-11-03 01:09

import breedingcows.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breedingcows', '0003_auto_20191102_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workposition',
            name='status',
            field=models.IntegerField(choices=[('Activo', 'ACTIVO'), ('Eliminado', 'ELIMINADO'), ('Suspendido', 'SUSPENDIDIO')], default=breedingcows.models.StatusType('Activo')),
        ),
    ]
