# Generated by Django 2.2.6 on 2019-11-11 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breedingcows', '0004_auto_20191102_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workposition',
            name='leaving_date',
        ),
        migrations.DeleteModel(
            name='Animal',
        ),
    ]
