# Generated by Django 2.2.6 on 2019-11-11 19:48

import breedingcows.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breedingcows', '0005_auto_20191111_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='workposition',
            name='position',
            field=models.CharField(choices=[('Dueño', 'DUEÑO'), ('Peón', 'PEON'), ('Veterinario', 'VETERINARIO')], default=breedingcows.models.PositionType('Dueño'), max_length=50),
        ),
        migrations.AlterField(
            model_name='workposition',
            name='status',
            field=models.CharField(choices=[('Activo', 'ACTIVO'), ('Eliminado', 'ELIMINADO'), ('Suspendido', 'SUSPENDIDIO')], default=breedingcows.models.StatusType('Activo'), max_length=50),
        ),
    ]
