# Generated by Django 2.2.6 on 2020-01-05 21:30

import breedingcows.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breedingcows', '0007_auto_20191220_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breedingcows',
            name='status',
            field=models.CharField(choices=[('Activo', 'ACTIVO'), ('Eliminado', 'ELIMINADO'), ('Suspendido', 'SUSPENDIDIO')], default=breedingcows.models.StatusType('Activo'), max_length=50),
        ),
    ]
