# Generated by Django 2.2.6 on 2020-04-09 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20200222_1558'),
        ('breedingcows', '0008_auto_20200105_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='breedingcows',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.Contact'),
        ),
    ]
