# Generated by Django 2.2.6 on 2020-06-22 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breedingcows', '0009_breedingcows_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breedingcows',
            old_name='location',
            new_name='address',
        ),
        migrations.AddField(
            model_name='breedingcows',
            name='province',
            field=models.CharField(default='', max_length=50),
        ),
    ]
