# Generated by Django 2.2.6 on 2020-06-22 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breedingcows', '0010_auto_20200621_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breedingcows',
            name='status',
        ),
        migrations.RemoveField(
            model_name='workposition',
            name='status',
        ),
        migrations.AddField(
            model_name='breedingcows',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
