# Generated by Django 2.2.6 on 2020-06-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breedingcows', '0012_auto_20200622_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breedingcows',
            name='address',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='breedingcows',
            name='province',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
