# Generated by Django 2.2.6 on 2019-10-12 19:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreedingCows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='', max_length=50)),
                ('entry_date', models.DateTimeField(blank=True, null=True)),
                ('leaving_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('a', 'Activo'), ('e', 'Eliminado')], default='a', help_text='Estado del Rodeo de Cría', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flock_number', models.IntegerField(blank=True, default=0, null=True)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('entry_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('leaving_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_date', models.DateTimeField(blank=True, null=True)),
                ('weight', models.DecimalField(decimal_places=15, max_digits=30)),
                ('reproductive_status', models.CharField(blank=True, choices=[('p', 'Positivo'), ('n', 'Negativo')], default='p', help_text='Estado reproductorio del animal', max_length=1)),
                ('animal_type', models.CharField(blank=True, choices=[('v', 'Vaca'), ('va', 'Vaquillona'), ('t', 'Toro'), ('te', 'ternero')], default='t', help_text='Estado reproductorio del animal', max_length=1)),
                ('breeding_cows', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breedingcowsapp.BreedingCows')),
            ],
        ),
    ]
